"""changed start_time and end_time for availability and bookings model to be strings instead of time object

Revision ID: 246b1de9a33b
Revises: ae5dc31128e8
Create Date: 2024-08-27 20:24:04.725958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246b1de9a33b'
down_revision = 'ae5dc31128e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=False)

    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
